apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cart-app
  template:
    metadata:
      labels:
        app: cart-app
    spec:
      containers:
        - name: cart-app
          image: registry.digitalocean.com/cart/cart-image:latest
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: cart-app-service
spec:
  selector:
    app: cart-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer